import { InitSDKOptions, LogEventOptions , AppsFlyerLinkGeneratorArgs, AppsFlyerConsentArgs} from './index';
declare const initSdk: (args: InitSDKOptions) => Promise<unknown>;
declare const startSdk: () => void;
declare const logEvent: (args: LogEventOptions) => Promise<unknown>;
declare const stop: (isStopped: boolean) => Promise<unknown>;
declare const setConsentData: (consent: AppsFlyerConsentArgs) => Promise<unknown>;
declare const enableTCFDataCollection: (shouldCollect: boolean) => Promise<unknown>;
declare const setCustomerUserId: (userId: string) => Promise<unknown>;
declare const setAppInviteOneLink: (link: string) => Promise<unknown>;
declare const getAppsFlyerUID: () => string;
declare const generateInviteUrl: (args: AppsFlyerLinkGeneratorArgs) => Promise<unknown>;
export { initSdk, startSdk, logEvent, stop, setCustomerUserId, setAppInviteOneLink, generateInviteUrl, getAppsFlyerUID, enableTCFDataCollection, setConsentData, };
